### ISSUE TITLE
对于fepack的一些疑问

### ISSUE THREAD

**Issue by Ge-yuan-jun** [bravf/fepack#1]
无意中浏览到您的开源项目，有一点点疑问想请教一下：
1. `fepack`与`webpack`的异同
2. `fepack`的适用场景是哪些？
3. 有没有一些文章关于这款打包工具的源码解析呢？最近对打包工具比较感兴趣

**Comment by bravf** [comment]
首先感谢你的关注。

1、fepack更倾向于功能内置，不插件化，也就意味着配置更少，但放弃插件化，就得不到社区的贡献，在新功能适配上会跟不上节奏。

2、fepack同其他构件工具一样做的事情基本一样，使用场景也基本相同。

3、暂时并没有文章介绍。

自己研发构建工具的好处是，可以随时根据公司的实际情况做调整，如果用开源工具，可能不太好改，或者就需要等社区的反馈了。
